# Pyrefly Static Analysis & Language Server Configuration
# https://pyrefly.org/

python-interpreter-path = ".venv/Scripts/python.exe"
search-path = [".", "classfellow_web"]
disable-type-errors-in-ide = true
preset = "off"
