# Generated by Django 5.1.15 on 2026-09-17 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("topic_covered", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="batch_sessions",
                        to="students.classgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch Lecture Session",
                "verbose_name_plural": "Batch Lecture Sessions",
                "db_table": "batch_sessions",
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Present", "Present"),
                            ("Absent", "Absent"),
                            ("Late", "Late"),
                            ("Leave", "Leave"),
                        ],
                        default="Present",
                        max_length=20,
                    ),
                ),
                ("reason_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="attendance_records",
                        to="students.enrollment",
                    ),
                ),
                (
                    "recorded_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_logs",
                        to="attendance.batchsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "db_table": "attendance_records",
                "indexes": [
                    models.Index(
                        fields=["enrollment", "attendance_date"],
                        name="idx_attendance_enrollment_date",
                    ),
                    models.Index(
                        fields=["attendance_date", "status"],
                        name="idx_attendance_date_status",
                    ),
                    models.Index(fields=["batch_session"], name="idx_attendance_batch"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("enrollment", "attendance_date"),
                        name="uq_attendance_enrollment_date",
                    )
                ],
            },
        ),
    ]
