# Generated by Django 5.1.15 on 2026-09-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_campus"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionBackupSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Original snapshot filename.", max_length=255
                    ),
                ),
                (
                    "file_size_bytes",
                    models.BigIntegerField(help_text="File size in bytes."),
                ),
                (
                    "sha256_hash",
                    models.CharField(
                        help_text="Cryptographic SHA-256 hex checksum.", max_length=64
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "desktop_machine_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Client machine hardware ID.",
                        max_length=100,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Originating IP address.", null=True
                    ),
                ),
                (
                    "backup_file",
                    models.FileField(
                        help_text="Snapshot archive file.", upload_to="uploads/backups/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Institution Backup Snapshot",
                "verbose_name_plural": "Institution Backup Snapshots",
                "db_table": "institution_backups",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
