# Generated by Django 5.1.15 on 2026-09-17 17:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_institutionbackupsnapshot"),
        ("students", "0002_classgroup_campus"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Circular heading or subject.", max_length=200
                    ),
                ),
                (
                    "urdu_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Urdu Nastaliq notice title.",
                        max_length=250,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Detailed circular announcement body."),
                ),
                (
                    "urdu_content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Urdu Nastaliq announcement body.",
                    ),
                ),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("FeeReminder", "Fee Reminder"),
                            ("ExamSchedule", "Exam Schedule"),
                            ("Holiday", "Holiday Announcement"),
                            ("General", "General Notice"),
                        ],
                        default="General",
                        help_text="Category of circular.",
                        max_length=50,
                    ),
                ),
                (
                    "issued_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Official publication date.",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, help_text="Visibility toggle."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_campus",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific campus scope (null applies to all campuses).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notices",
                        to="core.campus",
                    ),
                ),
                (
                    "target_class",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific class group scope (null applies to all classes).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notices",
                        to="students.classgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institution Notice",
                "verbose_name_plural": "Institution Notices",
                "db_table": "institution_notices",
                "ordering": ["-issued_date", "-created_at"],
            },
        ),
    ]
