# Generated by Django 5.1.15 on 2026-09-17 17:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_institutionbackupsnapshot"),
        ("examinations", "0001_initial"),
        ("students", "0002_classgroup_campus"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Institutional employee code (e.g., EMP-1001).",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "urdu_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Urdu Nastaliq staff name.",
                        max_length=150,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        help_text="e.g. Senior Teacher, Accountant, Lab Assistant, Principal.",
                        max_length=100,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        default="Administration",
                        help_text="e.g. Science, Arts, Administration.",
                        max_length=100,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Normalized primary contact (03XXXXXXXXX).",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "national_id_cnic",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="NADRA CNIC number.",
                        max_length=30,
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monthly base remuneration in PKR.",
                        max_digits=12,
                    ),
                ),
                ("joining_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campus",
                    models.ForeignKey(
                        help_text="Campus or branch assignment.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="staff_members",
                        to="core.campus",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Optional linked application login account.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Member",
                "verbose_name_plural": "Staff Members",
                "db_table": "staff_members",
                "ordering": ["employee_id"],
            },
        ),
        migrations.CreateModel(
            name="StaffSubjectAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_allocations",
                        to="core.academicsession",
                    ),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_allocations",
                        to="students.classgroup",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="staff.staff",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_allocations",
                        to="examinations.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Subject Allocation",
                "verbose_name_plural": "Staff Subject Allocations",
                "db_table": "staff_allocations",
            },
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(fields=["employee_id"], name="idx_staff_emp_id"),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["first_name", "last_name"], name="idx_staff_names"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(fields=["phone"], name="idx_staff_phone"),
        ),
        migrations.AddConstraint(
            model_name="staffsubjectallocation",
            constraint=models.UniqueConstraint(
                fields=("staff", "class_group", "subject", "academic_session"),
                name="unique_staff_class_subject_session",
            ),
        ),
    ]
