# Generated by Django 5.1.15 on 2026-09-17 14:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Class 9, Class 10, Matric Physics.",
                        max_length=100,
                    ),
                ),
                (
                    "section_or_batch",
                    models.CharField(
                        help_text="e.g. Section A, Evening Batch.", max_length=100
                    ),
                ),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("SchoolClass", "School Class"),
                            ("AcademyBatch", "Academy Batch"),
                        ],
                        default="SchoolClass",
                        max_length=50,
                    ),
                ),
                (
                    "monthly_tuition_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="class_groups",
                        to="core.academicsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Group",
                "verbose_name_plural": "Class Groups",
                "db_table": "class_groups",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admission_number",
                    models.CharField(
                        help_text="Institutional registration number.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "urdu_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Urdu Nastaliq student name.",
                        max_length=150,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "b_form_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="NADRA B-Form number.",
                        max_length=30,
                    ),
                ),
                ("guardian_name", models.CharField(max_length=100)),
                (
                    "guardian_urdu_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "guardian_relation",
                    models.CharField(default="Father", max_length=50),
                ),
                (
                    "guardian_phone",
                    models.CharField(
                        help_text="Normalized primary contact (03XXXXXXXXX).",
                        max_length=20,
                    ),
                ),
                (
                    "guardian_whatsapp",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "guardian_cnic",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("residential_address", models.TextField(blank=True, default="")),
                (
                    "emergency_contact",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "db_table": "students",
                "indexes": [
                    models.Index(
                        fields=["admission_number"], name="idx_students_admission_no"
                    ),
                    models.Index(
                        fields=["first_name", "last_name"], name="idx_students_names"
                    ),
                    models.Index(
                        fields=["guardian_phone"], name="idx_students_guardian_phone"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "roll_number",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "enrollment_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Transferred", "Transferred"),
                            ("Withdrawn", "Withdrawn"),
                            ("Graduated", "Graduated"),
                        ],
                        default="Active",
                        max_length=30,
                    ),
                ),
                (
                    "custom_discount_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="enrollments",
                        to="students.classgroup",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="enrollments",
                        to="core.academicsession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="enrollments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
                "db_table": "enrollments",
            },
        ),
        migrations.AddConstraint(
            model_name="classgroup",
            constraint=models.UniqueConstraint(
                fields=("session", "name", "section_or_batch"),
                name="uq_class_groups_session_name_section",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["student"], name="idx_enrollments_student"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["class_group", "session"], name="idx_enrollments_class_session"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["status"], name="idx_enrollments_status"),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "class_group", "session"),
                name="uq_enrollments_student_class_session",
            ),
        ),
    ]
