# Generated by Django 5.1.15 on 2026-09-17 16:49

import django.db.models.deletion
from django.db import migrations, models


def assign_default_campus(apps, schema_editor):
    Campus = apps.get_model("core", "Campus")
    ClassGroup = apps.get_model("students", "ClassGroup")

    default_campus, _ = Campus.objects.get_or_create(
        code="MBC",
        defaults={
            "name": "Main Campus",
            "is_active": True,
        },
    )
    ClassGroup.objects.filter(campus__isnull=True).update(campus=default_campus)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_campus"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classgroup",
            name="campus",
            field=models.ForeignKey(
                blank=True,
                help_text="Branch or campus facility.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="classes",
                to="core.campus",
            ),
        ),
        migrations.RunPython(assign_default_campus, reverse_code=migrations.RunPython.noop),
    ]
