# Generated by Django 5.1.15 on 2026-09-17 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("urdu_name", models.CharField(blank=True, default="", max_length=150)),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "db_table": "subjects",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("MonthlyTest", "Monthly Test"),
                            ("TermExam", "Term Examination"),
                            ("AnnualExam", "Annual Examination"),
                            ("MockTest", "Mock Test"),
                        ],
                        default="TermExam",
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="exams",
                        to="core.academicsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Examination",
                "verbose_name_plural": "Examinations",
                "db_table": "exams",
            },
        ),
        migrations.CreateModel(
            name="ExamSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maximum_marks",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
                ),
                (
                    "passing_marks",
                    models.DecimalField(decimal_places=2, default=33.0, max_digits=6),
                ),
                (
                    "weightage_percent",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                ("exam_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="exam_subjects",
                        to="students.classgroup",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_subjects",
                        to="examinations.exam",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="exam_subjects",
                        to="examinations.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Subject Configuration",
                "verbose_name_plural": "Exam Subject Configurations",
                "db_table": "exam_subjects",
            },
        ),
        migrations.CreateModel(
            name="GradingTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_name", models.CharField(max_length=20)),
                ("min_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("max_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "gpa_point",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                (
                    "remarks_en",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "remarks_ur",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("is_passing", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="grading_tiers",
                        to="core.academicsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grading Tier",
                "verbose_name_plural": "Grading Tiers",
                "db_table": "grading_tiers",
            },
        ),
        migrations.CreateModel(
            name="Mark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks_obtained", models.DecimalField(decimal_places=2, max_digits=6)),
                ("is_absent", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="marks",
                        to="students.enrollment",
                    ),
                ),
                (
                    "exam_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="examinations.examsubject",
                    ),
                ),
                (
                    "recorded_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_marks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mark Record",
                "verbose_name_plural": "Mark Records",
                "db_table": "marks",
            },
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.UniqueConstraint(
                fields=("session", "name"), name="uq_exams_session_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="gradingtier",
            constraint=models.UniqueConstraint(
                fields=("session", "grade_name"), name="uq_grading_tiers_session_grade"
            ),
        ),
        migrations.AddIndex(
            model_name="mark",
            index=models.Index(fields=["enrollment"], name="idx_marks_enrollment"),
        ),
        migrations.AddIndex(
            model_name="mark",
            index=models.Index(
                fields=["exam_subject", "enrollment"], name="idx_marks_lookup"
            ),
        ),
        migrations.AddConstraint(
            model_name="mark",
            constraint=models.UniqueConstraint(
                fields=("exam_subject", "enrollment"),
                name="uq_marks_exam_subject_enrollment",
            ),
        ),
        migrations.AddIndex(
            model_name="examsubject",
            index=models.Index(
                fields=["exam", "class_group"], name="idx_exam_subjects_lookup"
            ),
        ),
        migrations.AddConstraint(
            model_name="examsubject",
            constraint=models.UniqueConstraint(
                fields=("exam", "class_group", "subject"), name="uq_exam_class_subject"
            ),
        ),
    ]
