# Generated by Django 5.1.15 on 2026-09-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Administrator"),
                    ("Principal", "Principal"),
                    ("Cashier", "Cashier"),
                    ("Teacher", "Teacher"),
                    ("Parent", "Parent"),
                ],
                default="Cashier",
                help_text="Operational institutional role.",
                max_length=20,
            ),
        ),
    ]
