# Generated by Django 5.1.15 on 2026-09-17 14:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tuition, Admission, Lab, etc.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("urdu_name", models.CharField(blank=True, default="", max_length=150)),
                ("is_recurring", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Fee Head",
                "verbose_name_plural": "Fee Heads",
                "db_table": "fee_heads",
            },
        ),
        migrations.CreateModel(
            name="FeeInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month_year",
                    models.CharField(
                        help_text="Billing cycle (YYYY-MM).", max_length=10
                    ),
                ),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField()),
                ("valid_until", models.DateField()),
                (
                    "late_fee_surcharge",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_payable",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "net_due",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="invoices",
                        to="students.enrollment",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="invoices",
                        to="core.academicsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee Invoice",
                "verbose_name_plural": "Fee Invoices",
                "db_table": "fee_invoices",
            },
        ),
        migrations.CreateModel(
            name="FeeInvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fee_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="invoice_items",
                        to="fees.feehead",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="fees.feeinvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee Invoice Item",
                "verbose_name_plural": "Fee Invoice Items",
                "db_table": "fee_invoice_items",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("BankTransfer", "Bank Transfer"),
                            ("OnlineDeposit", "Online Deposit"),
                            ("Cheque", "Cheque"),
                        ],
                        default="Cash",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Issued", "Issued"),
                            ("Reversed", "Reversed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Issued",
                        max_length=30,
                    ),
                ),
                ("reversal_reason", models.TextField(blank=True, default="")),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payments",
                        to="fees.feeinvoice",
                    ),
                ),
                (
                    "recorded_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Receipt",
                "verbose_name_plural": "Payment Receipts",
                "db_table": "payments",
            },
        ),
        migrations.AddIndex(
            model_name="feeinvoice",
            index=models.Index(
                fields=["enrollment"], name="idx_fee_invoices_enrollment"
            ),
        ),
        migrations.AddIndex(
            model_name="feeinvoice",
            index=models.Index(
                fields=["month_year", "session"], name="idx_fee_invoices_cycle"
            ),
        ),
        migrations.AddIndex(
            model_name="feeinvoice",
            index=models.Index(
                fields=["valid_until"], name="idx_fee_invoices_valid_until"
            ),
        ),
        migrations.AddIndex(
            model_name="feeinvoice",
            index=models.Index(
                fields=["session", "valid_until"], name="idx_fee_invoices_session_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="feeinvoice",
            constraint=models.UniqueConstraint(
                fields=("enrollment", "month_year"),
                name="uq_fee_invoices_enrollment_month",
            ),
        ),
        migrations.AddIndex(
            model_name="feeinvoiceitem",
            index=models.Index(
                fields=["invoice"], name="idx_fee_invoice_items_invoice"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["invoice"], name="idx_payments_invoice"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["invoice", "status", "amount"],
                name="idx_payments_inv_status_amt",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["receipt_number"], name="idx_payments_receipt_no"
            ),
        ),
    ]
